package org.jboss.shamrock.maven.runner;

import java.io.File;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.jboss.shamrock.annotations.BuildStep;
import org.jboss.shamrock.annotations.BuildProducer;
import org.jboss.shamrock.annotations.BuildResource;
import org.jboss.shamrock.deployment.BuildProcessingStep;
import org.jboss.shamrock.deployment.RuntimePriority;
import org.jboss.shamrock.deployment.builditem.BytecodeOutputBuildItem;
import org.jboss.shamrock.deployment.builditem.ReflectiveClassBuildItem;
import org.jboss.shamrock.deployment.codegen.BytecodeRecorder;
import org.jboss.shamrock.runtime.ConfiguredValue;
import org.jboss.shamrock.undertow.runtime.UndertowDeploymentTemplate;

import io.undertow.server.HandlerWrapper;
import io.undertow.server.HttpHandler;

@BuildStep()
public class RuntimeCompilationSetup implements BuildProcessingStep {

    private static final Logger log = Logger.getLogger(RuntimeCompilationTemplate.class.getName());


    @BuildResource
    BytecodeOutputBuildItem bytecode;

    /**
     * TODO: remove once generated bytecode is correctly modeled as a produced build item
     * at the moment as this processor does not seem to produce anything it will not be invoked
     */
    @BuildResource
    BuildProducer<ReflectiveClassBuildItem> hack;

    @Override
    public void build() throws Exception {
        try {
            //don't do this if we don't have Undertow
            Class.forName("org.jboss.shamrock.undertow.ServletResourceProcessor");
        } catch (ClassNotFoundException e) {
            return;
        }

        String classesDir = System.getProperty("shamrock.runner.classes");
        if (classesDir != null) {
            try (BytecodeRecorder recorder = bytecode.addStaticInitTask(RuntimePriority.HOT_DEPLOYMENT_START_UNDERTOW)) {
                HandlerWrapper wrapper = recorder.getRecordingProxy(RuntimeCompilationTemplate.class).createHandlerWrapper();
                recorder.getRecordingProxy(UndertowDeploymentTemplate.class).startUndertowEagerly(new ConfiguredValue("http.port", "8080"), new ConfiguredValue("http.host", "localhost"), new ConfiguredValue("http.io-threads", ""), new ConfiguredValue("http.worker-threads", ""), wrapper);
            }
        }
    }


    public static class RuntimeCompilationTemplate {

        public HandlerWrapper createHandlerWrapper() {

            String classesDir = System.getProperty("shamrock.runner.classes");
            String sourcesDir = System.getProperty("shamrock.runner.sources");

            return new HandlerWrapper() {
                @Override
                public HttpHandler wrap(HttpHandler handler) {
                    ClassLoaderCompiler compiler = null;
                    try {
                        compiler = new ClassLoaderCompiler(Thread.currentThread().getContextClassLoader(), new File(classesDir));
                    } catch (Exception e) {
                        log.log(Level.SEVERE, "Failed to create compiler, runtime compilation will be unavailable", e);
                        return handler;
                    }
                    return new RuntimeUpdatesHandler(handler, Paths.get(classesDir), Paths.get(sourcesDir), compiler);
                }
            };
        }

    }
}
